#!/bin/sh
# Function to run command and check exit status
check_command() {
    $1
    if [ $? -ne 0 ]; then
        echo "${2} failed, aborting commit"
        exit 1
    fi
}

# Create a list of staged files
FILES=$(git diff --cached --name-only --diff-filter="AM" | sed 's| |\\ |g')

# Checking if the list is empty
if [ -z "$FILES" ]; then
    exit 0
fi

# Add the current script to the list of files to run when attempting a commit
CURRENT_FILE="${BASH_SOURCE[0]}"

# Create a list of staged files
FILES_UPDATED=$(echo "$FILES" | grep -E "(\.(js|ts|d\.ts|mt|jt|cjs|vue|jsx|tsx|json|html|css|scss)$|^${CURRENT_FILE}$)")

if [ -z "$FILES_UPDATED" ]; then
    exit 0
fi

check_command "npm run lint --if-present" "Linting"
check_command "npm run format --if-present -- -- --write" "Formatting"
check_command "npm run typecheck --if-present" "Typecheck"

# Add back the modified/prettified files to staging
echo "$FILES_UPDATED" | xargs git add

exit 0
