blank_issues_enabled: false
contact_links:
  - name: Propose an idea
    url: https://github.com/cawa-93/vite-electron-builder/discussions/categories/ideas
  - name: Ask a questions
    url: https://github.com/cawa-93/vite-electron-builder/discussions/categories/q-a
