runner:
  typecheck-main:
    cmd: npx vuedx-typecheck ./src/main --no-pretty --format rdjson
    errorformat:
      - rdjson
  typecheck-preload:
    cmd: npx @vuedx/vuedx-typecheck ./src/preload --no-pretty --format rdjson
    errorformat:
      - rdjson
  typecheck-renderer:
    cmd: npx vuedx-typecheck ./src/renderer --no-pretty --format rdjson
    errorformat:
      - rdjson
