#  Remove all releases in the project.
#  This job is required for the needs of the template itself
#  and should not be part of the application.
#  Please remove it.




name: Delete All Releases

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write # Allows this job to create releases

jobs:
  delete_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        run: |
          if [ "${{ github.repository }}" != "cawa-93/vite-electron-builder" ]; then
            echo "This workflow only runs in the cawa-93/vite-electron-builder repository."
            exit 1
          fi

      - uses: actions/checkout@v2
      - name: Delete All Releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          releases=$(gh release list | awk '{print $1}')
          for release in $releases; do
            gh release delete $release -y --cleanup-tag
          done
